version: '3.8'

services:
  movies:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: movie_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8009:8000"
    env_file:
      - ./app/.env.dev
    depends_on:
      - movies-db

  movies-db:
    image: postgres:15
    container_name: movie_db
    volumes:
      - movies_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=movies
      - POSTGRES_DB=movies_dev

volumes:
  movies_postgres_data:
